// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeWebApp.Data;

#nullable disable

namespace RecipeWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeWebApp.Models.Meal", b =>
                {
                    b.Property<string>("idMeal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("strArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strIngredient9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMealThumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMeasure9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strYoutube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMeal");

                    b.ToTable("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
